apiVersion: v1
kind: Service
metadata:
    name: "akspocdemo-ed82"
    labels:
        app: "akspocdemo-ed82"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akspocdemo-ed82"